### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by NixWasHere** [Hex1629/BotnetC2#3]
Hello, mind dropping me your discord? I am willing to continue my project with you and combine yours and mine together if you want to. 
Have a nice day, 
Nix.

**Comment by localuser-isback** [comment]
I could give some scripts aswell that you could add, ive got some working cloudflare bypass scripts and stuff if your interested

**Comment by NixWasHere** [comment]
@localuser-isback my discord is Niksazizu#8502
