### ISSUE TITLE
adding bots

### ISSUE THREAD

**Issue by H3ckforfun** [Hex1629/BotnetC2#6]
Hello, 
i got some problems with the bots. I updated my net and now i cant add bots anymore, i already tried the old bot but nothing adds bot to my net anymore.

**Comment by Hex1629** [comment]
New botnet?

**Comment by H3ckforfun** [comment]
It was working fine until i updated the net, i even tried to downgrade but doesnt work

**Comment by Hex1629** [comment]
next patchh
i found now

**Comment by Hex1629** [comment]
i have discord now?

**Comment by H3ckforfun** [comment]
i was the one from the call lol

**Comment by Hex1629** [comment]
pip install now?

**Comment by Hex1629** [comment]
can run now?
