### ISSUE TITLE
any idea to combine it with discord bot?

### ISSUE THREAD

**Issue by anonsecbotnetstudent123** [Hex1629/BotnetC2#8]

**Comment by Hex1629** [comment]
I DON'T KNOW BECAUSE I TEST ATTACK WITH PYF METHODS CAN HIT 15K FROM DISCORD BOT

**Comment by localuser-isback** [comment]
guilded bots are alot easyer 15k isnt alot.... i hit 200k on a free VPS with my script (not even a botnet) LOL

**Comment by anonsecbotnetstudent123** [comment]
if you have time, please test my sites: https://new.anontoken1.tk/mygirlfriend.jpg thanks a lot!
